### PR TITLE
changes for #809 (error message for empty workflow)

### PR DESCRIPTION
**Pull request by nicolecastillo**
Handling error message for empty workflow and adds the test cases for it.

### CODE REVIEW

**Comment by edeediong** [comment]
@nicolecastillo Thanks for working on this. Before your PR is reviewed you'd need to fix the failing builds. I checked the logs and it seems you haven't formatted the codes to conform with black. [This](https://github.com/systemslab/popper/blob/master/CONTRIBUTING.md#codestyle) explains what you need to do to fix that. Cheers!

**Comment by nicolecastillo** [comment]
@edeediong Thank you, that was the problem!

**Comment by JayjeetAtGithub** [comment]
@nicolecastillo Thanks a lot. Maybe we can take this opportunity to add a file reader abstraction, maybe something like a `read_file(path, type)` function in `utils.py`, which would be used to read both the workflow file, i.e. `wf.yml` and config file, i.e. `config.yml`. The abstraction would: 

1. Check if the path is `not None`.
2. Check if the extension of the file requested is `== type`.
3. Check if the file exists.
4. Check if the file is empty.

If all the checks pass, read the contents into a `dict` and return.

**Comment by nicolecastillo** [comment]
@JayjeetAtGithub Sure, I'll look into it and work on that.

**Comment by ivotron** [comment]
thanks a lot @nicolecastillo , let us know if you have any question!

**Comment by ivotron** [comment]
the recent changes on `master` are causing this to be conflicted. So maybe it would be better to close it and port the changes to the tip of `master` in order to address #809. @nicolecastillo if it works better for you, maybe we can also break this in two, and work on what Jayjeet and Eddie suggested separately as another PR.

**Pull request closed without merging**
