### PR TITLE
Color functionality added for display of dict and list objects

### PR DESCRIPTION
**Pull request by UjjwalAyyangar**
This addresses the issues #223 and #226

### CODE REVIEW

**Comment by UjjwalAyyangar** [comment]
The build fails after adding the pprint functionality for #226

**Comment by UjjwalAyyangar** [comment]
The build keeps failing because of the pprint functionality that has been added. 
I will look into this.

**Comment by UjjwalAyyangar** [comment]
Removed the indent of pprint to make it consistent with the tests.

**Comment by ankan17** [comment]
It'd be good if you can merge the two commits @UjjwalAyyangar

**Comment by ivotron** [comment]
Cool! Thanks a lot for working on this. I should have looked better into `pprint`, what we'd really want for `dict` and `list` is to display them in YAML's [block format](http://www.yaml.org/spec/1.2/spec.html#id2797293). For lists, this is:

```yaml
- one
- two
- three
```

and for dictionaries, this is:

```yaml
key1: value1
key2: value2
key3: value3
```

**Comment by ivotron** [comment]
@ankan17 no worries on having to combine commits, github squashes commits automatically:

screen shot 2018-03-04 at 15 05 53

**Comment by ivotron** [comment]
looks awesome, shining colors 😄 thanks a lot for working on this!

**Pull request merged**
