### PR TITLE
Improved the tests

### PR DESCRIPTION
**Pull request by vipulchhabra99**
The test cases had minor problems in coding style.
Improved them by going through [link](https://github.com/koalaman/shellcheck/wiki/SC2251)
This is the pr for #750 .

### CODE REVIEW

**Comment by ivotron** [comment]
thanks a lot for working on this @vipulchhabra99!  Can you please rebase branch `update-actionsnpm-reference`. I added a fix for the `actions/npm` errors observed there.

**Comment by vipulchhabra99** [comment]
ok sure @ivotron.

**Comment by vipulchhabra99** [comment]
@ivotron can you please check this why its still failing?

**Comment by ivotron** [comment]
@vipulchhabra99, as pointed out in [shellcheck's documentation](https://github.com/koalaman/shellcheck/wiki/SC2251) before the fix you introduced to the test scripts, we were basically ignoring all `! cmd` tests. So it is likely that what we observe in travis is an actual error (i.e. an expectation not being met).

**Comment by vipulchhabra99** [comment]
Oh, I misunderstood it oppositely, Sorry for the inconvenience caused I am updating it again.

**Comment by ivotron** [comment]
thanks a lot @vipulchhabra99 . I added your commits to PR #754, as there were other couple of things that needed to be fixed.

**Pull request closed without merging**
