### PR TITLE
Added docstrings to classes and functions

### PR DESCRIPTION
**Pull request by vipulchhabra99**
Added the docstrings for the classes and functions.

This is the pr for the issue #700.

### CODE REVIEW

**Comment by ivotron** [comment]
@vipulchhabra99 can you please rebase master? the issue with improper use of the `!` bash operator has been merged. thanks!

**Comment by vipulchhabra99** [comment]
@ivotron Yeah, Sure.

**Comment by ivotron** [comment]
many thanks for working on this PR @vipulchhabra99! this is a great start. In order to merge this PR, we need to apply the [Google Python Style convention for docstrings](http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) to all the code, meaning we have to document the arguments (and return behavior) for every method/function, as well as adding docstrings for all classes. For examples you can take a look [here](http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings).

**Comment by vipulchhabra99** [comment]
Hi, @ivotron I have updated the pr with desirable changes, I have left a few variables since I was not able to understand their usage. If still there are more changes or anything that I could have missed please do inform me, I would surely try to complete them.

**Comment by ivotron** [comment]
thank you very much @vipulchhabra99 this is awesome work! Answers to your queries made on Gitter:
  * `ctx` is defined by the click package. We can add a link to the click documentation, for example [this section](https://click.palletsprojects.com/en/7.x/commands/#nested-handling-and-contexts).
  * `wf` is an instance of the `Worfklow` class.
  * `frame` received in `cli.signal_handler()` is described [here](https://docs.python.org/3/library/signal.html#signal.signal) which points to [this link](https://docs.python.org/3/reference/datamodel.html#frame-objects), so we can point to either of these two links.
  * `mod` in `cli.PopperCLI.get_command()` is the `cli` function that any of the `cmd_*.py` files define.
  *  `wid` is a workflow ID produced by a `utils.get_id()`
  *  `r` in `scm.get_default_branch` is a [`git.Repo`](https://gitpython.readthedocs.io/en/stable/tutorial.html#meet-the-repo-type) object

**Comment by vipulchhabra99** [comment]
Thanks a lot, @ivotron, I will update the PR and make desired changes.

**Comment by ivotron** [comment]
the other thing we could add to the `cli.py` file is a link to [this page](https://click.palletsprojects.com/en/7.x/commands/#custom-multi-commands) of the Click documentation, which is where we based the initial CLI skeleton from. That page basically explains the objects defined and the main rationale behind lazily loading command modules.

**Comment by vipulchhabra99** [comment]
Thanks for reviewing @ivotron, I have updated with original links but they are long enough and show pep8 styling errors.

**Comment by ivotron** [comment]
thanks a lot @vipulchhabra99 !

**Comment by vipulchhabra99** [comment]
Thanks @ivotron  for helping me out during this entire process. It was a nice learning experience.

**Pull request merged**
