### PR TITLE
Fixes #504 Adds .workflow validation

### LINKED ISSUE #504: cli: validate .workflow file
As part of `popper run`, add a routine that validates a `.workflow` file in order to check that the expected elements of the workflow are present, as described in the Github actions documentation for both [Workflow](https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#workflow-blocks) and [Action](https://developer.github.com/actions/creating-workflows/workflow-configuration-options/#action-blocks) blocks.

The idea is to show better messages to a user in the command line as opposed to the current behavior which is a Python dump of the trace. For example, for a `.workflow` file that is missing a `resolves` keyword in the Workflow block, this is the current output:

```
$ popper run
Traceback (most recent call last):
  File "/Users/ivo/src/popper/cli/bin/popper", line 30, in <module>
    popper.cli.cli()
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 731, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 706, in main
    rv = self.invoke(ctx)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 1080, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 907, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 544, in invoke
    return callback(*args, **kwargs)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/ivo/src/popper/cli/bin/vendor/click/click/core.py", line 544, in invoke
    return callback(*args, **kwargs)
  File "/Users/ivo/src/popper/cli/popper/commands/cmd_run.py", line 35, in cli
    pipeline = Workflow(wfile, workspace)
  File "/Users/ivo/src/popper/cli/popper/gha.py", line 37, in __init__
    self.normalize()
  File "/Users/ivo/src/popper/cli/popper/gha.py", line 77, in normalize
    self.wf['resolves'] = wf_block['resolves']
KeyError: 'resolves'
```

Instead, we'd like something more friendly, like an `Expecting 'resolves' keyword` message.

### PR DESCRIPTION
**Pull request by JayjeetAtGithub**
Added validation rules to validate .workflow files more efficiently and throw nice error messages when validation error occurs.

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
@ivotron Please review

**Comment by JayjeetAtGithub** [comment]
@ivotron Will be updating the PR soon

**Comment by JayjeetAtGithub** [comment]
@ivotron I have updated the PR accordingly, Please review. I am having a problem that when i am running
`popper run --wfile ci/cli.workflow`  this error comes
```
Traceback (most recent call last):
  File "/usr/local/bin/popper", line 9, in <module>
    load_entry_point('popper==2.0.0.dev0', 'console_scripts', 'popper')()
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/jayjeet/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/commands/cmd_run.py", line 37, in cli
    pipeline.run(action)
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/gha.py", line 196, in run
    self.run_stage(s)
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/gha.py", line 201, in run_stage
    self.wf['action'][a]['runner'].run()
  File "/usr/local/lib/python2.7/dist-packages/popper-2.0.0.dev0-py2.7.egg/popper/gha.py", line 340, in run
    cmd[0] = os.path.join('./', cmd[0])
TypeError: 'unicode' object does not support item assignment
```

Due to this i am also unable to write tests in `validate-syntax.sh` file. Please guide me

**Comment by ivotron** [comment]
thanks @JayjeetAtGithub , that's due to how python2.7 deals with strings. I've created #521 to deal with this separately. In the meantime, you can either install python3 on your machine, or let Travis run the tests for you (tests passed on Travis).

BTW, could you please rebase `master`? I pushed a couple of changes to the tests. Also, there are some PEP8 issues, as pointed by the pep8speaks bot above.

**Comment by JayjeetAtGithub** [comment]
@ivotron Sure ! i am updating my PR by rebasing against master and fixing the pep8 issues.

**Comment by JayjeetAtGithub** [comment]
@ivotron Should i add `popper run --wfile ci/cli.workflow` to `validate-syntax.sh` file ?

**Comment by ivotron** [comment]
@JayjeetAtGithub sorry, I hadn't merged the commit I wanted you to rebase. Can you please rebase again? You can take a look at [this script](https://github.com/systemslab/popper/blob/751ba18c9fb125d14a4e619be7018fbd5c25a8b0/ci/test/reuse) to get an idea of how to write a test that is executing a workflow. In your case, for each of the things that a workflow file should correctly do, you could define a `.workflow` file that has something not correctly specified, and then test to see if `popper run` catches it and properly shows a friendly error message

**Comment by JayjeetAtGithub** [comment]
@ivotron I am working on the tests . Can you please review and if ok merge the pr ?

**Comment by JayjeetAtGithub** [comment]
@ivotron I was testing the validate function , when i ran into this

`isinstance(wf_block['on'], str)`  is `False` as `type(wf_block['on'])` is coming `unicode`.

Please tell me what to do with this

**Comment by JayjeetAtGithub** [comment]
@ivotron I have checked the validation feature against various wrongly configured .workflow files and it is working correctly, throwing correct  errors at correct places. Please review.

**Comment by ivotron** [comment]
@JayjeetAtGithub awesome! Would it be possible for you to add the test cases you have tried as part of this PR. You can look at [this script](https://github.com/systemslab/popper/blob/751ba18c9fb125d14a4e619be7018fbd5c25a8b0/ci/test/reuse) to see how this is done as part of a test. You can add those to the `validate-syntax` script you have in this PR and then invoke it from the CI pipeline we have [here](https://github.com/systemslab/popper/tree/master/ci)

**Comment by JayjeetAtGithub** [comment]
@ivotron yeah...updating soon

**Comment by JayjeetAtGithub** [comment]
@ivotron I am closing this PR. I had some synchronization problems. I will be opening a fresh one

**Pull request closed without merging**
