### PR TITLE
Fixes #248 Implement a popper add sub-command

### LINKED ISSUE #248: cli: 'popper add' command

### PR DESCRIPTION
**Pull request by ankan17**
A new sub-command add is added which adds a pipeline to the repo from existing popperized repositories on github and also updates the .popper.yml as required.

### CODE REVIEW

**Comment by ankan17** [comment]
PyGithub did not have the necessary functionalities to download files or directories from github. So I had to implement it with the requests module. Also it looks cleaner this way. What do you say @ivotron ?

**Comment by UjjwalAyyangar** [comment]
@ankan17 Can you add requests as a sub module?
For external dependencies, we are also vendoring them in cli/bin/vendor. 

Also, can you please use git commit --amend ?

**Comment by ankan17** [comment]
Sure I'll add it to the vendors

**Comment by ankan17** [comment]
Done @ivotron

**Comment by ivotron** [comment]
cool! Thanks a lot!

**Pull request merged**
