### PR TITLE
Kubernetes runner

### PR DESCRIPTION
**Pull request by ivotron**

### CODE REVIEW

**Comment by edeediong** [comment]
@ivotron .. Adding a Kubernetes runner? How can I help? I just started doing a few things with K8.

**Comment by ivotron** [comment]
hey @edeediong , thanks a lot for reaching out! Yes, there's WIP in #800, I can walk you through that if you want, so that you can take over that feature. Would that work?

**Comment by edeediong** [comment]
Yes sure, that'd work. Please walk me through it

**Comment by edeediong** [comment]
@ivotron while looking at the code, I looked at the Travis checks. Seem to be failing due to STEP. All the errors all seem connected to a lack of STEP.

**Comment by edeediong** [comment]
Also, `RESMAN` key is causing some kinda issues. I looked through the *runner_kubernetes.py*. Seems you're trying to prepare a file that can enable popper run on a Kubernetes engine or so.

**Comment by ivotron** [comment]
superseded by #808

**Pull request closed without merging**
