### PR TITLE
Fix missing action recursive in cli.workflow

### PR DESCRIPTION
**Pull request by akashrajr1**
Addresses #536

### CODE REVIEW

**Comment by akashrajr1** [comment]
@ivotron can you help me resolve `travis ci` build fail?

**Comment by akashrajr1** [comment]
[This](https://travis-ci.org/systemslab/popper/jobs/507535783#L897-L902) seems to indicate only `main.workflow` was run. But [these](https://travis-ci.org/systemslab/popper/jobs/507535783#L890-L894) indicate that `popper run --recursive` has generated output for these workflows in out and thus got the output it needed
And since `set -x` wasn't working properly for nested loops I had to reset it here. Maybe just hit and trial will help?https://github.com/systemslab/popper/blob/8dbffd68c68b34e045a26ee0c2aa0082982ac11b/ci/test/recursive#L36-L48

**Comment by akashrajr1** [comment]
@ivotron just found something instrumental!  
https://github.com/systemslab/popper/blob/8dbffd68c68b34e045a26ee0c2aa0082982ac11b/ci/test/recursive#L45
Arithmetic expansions actually seem to break the code for some unknown reason! So I had to bypass it by counting no of `success`
https://github.com/systemslab/popper/blob/a2877e8d407ceca4211d4f2d262af6818e9acc38/ci/test/recursive#L44-L49
All of them seem to fail. For future references, these commands fail the build
```
i=$((i+1)) 
i=$((i++)) 
((i=i+1))  
((i+=1))   
((i++))    
((++i))    
let "i=i+1"
let "i+=1" 
let "i++"  
let i=i+1  
let i+=1   
let i++    
```

**Comment by ivotron** [comment]
@akashrajr1 good catch!

**Comment by ivotron** [comment]
thanks a lot!

**Pull request merged**
